/* Creates all indexes. This is for SQL 2012 only */
/* For: MS SQL 2008 and above */




SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO


CREATE PRIMARY XML INDEX [IX_xmlPersonName] ON [dbo].[Users]
(
	[PersonName]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO




SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO


CREATE PRIMARY XML INDEX [IX_xmlTitle] ON [dbo].[Node]
(
	[xmlTitle]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO





CREATE FULLTEXT CATALOG [FTC_Node]WITH ACCENT_SENSITIVITY = OFF
AS DEFAULT
GO


CREATE FULLTEXT CATALOG [FTC_Users]WITH ACCENT_SENSITIVITY = OFF
AS DEFAULT
GO



CREATE FULLTEXT INDEX ON [dbo].[Users] KEY INDEX [PK_Users] ON ([FTC_Users]) WITH (CHANGE_TRACKING AUTO)
GO
ALTER FULLTEXT INDEX ON [dbo].[Users] ADD ([PersonName])
GO
ALTER FULLTEXT INDEX ON [dbo].[Users] ADD ([xmlProfile])
GO
ALTER FULLTEXT INDEX ON [dbo].[Users] ADD ([xmlLink])
GO
ALTER FULLTEXT INDEX ON [dbo].[Users] ENABLE
GO